apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: emumba-assessment
spec:
  selector:
    app.kubernetes.io/name: frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
