apiVersion: apps/v1
kind: Deployment
metadata:
  name: quoteservice
  labels:
    app.kubernetes.io/name: quoteservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: quoteservice
  template:
    metadata:
      labels:
        app.kubernetes.io/name: quoteservice
    spec:
      containers:
        - name: quoteservice
          image: annasali2/emumba-quoteservice:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: quoteservice-config
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
