apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: quoteservice
  namespace: emumba-assessment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: quoteservice
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
