apiVersion: v1
kind: Service
metadata:
  name: quoteservice
  namespace: emumba-assessment
spec:
  selector:
    app.kubernetes.io/name: quoteservice
  ports:
  - port: 5000   # TODO confirm
    targetPort: 5000
