apiVersion: v1
kind: Service
metadata:
  name: quoteservice
  namespace: emumba-assessment
spec:
  selector:
    app.kubernetes.io/name: quoteservice
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    protocol: TCP
  type: ClusterIP
