apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
  labels:
    app.kubernetes.io/name: apigateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: apigateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: apigateway
    spec:
      containers:
        - name: apigateway
          image: annasali2/emumba-apigateway:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: apigateway-config
          readinessProbe:
            httpGet:
              path: /api/status
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000 
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
