apiVersion: v1
kind: Service
metadata:
  name: apigateway
  namespace: emumba-assessment
spec:
  selector:
    app.kubernetes.io/name: apigateway
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
