apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq-standard
  namespace: emumba-assessment
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "30"
